FROM mcr.microsoft.com/dotnet/sdk:3.1 AS apigateway-build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out 

# Build runtime image
FROM mcr.microsoft.com/dotnet/sdk:3.1 AS apigateway
WORKDIR /app
COPY --from=apigateway-build /app/out .
ENTRYPOINT ["dotnet", "ApiGateway.dll", "--urls", "http://*:5000;https://*:5001"]